apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: final
data:
  S3_BUCKET_NAME: background-image-project
  BACKGROUND_IMAGE_KEY: OIP.jpeg
  AWS_REGION: us-east-1
  YOUR_NAME: "Group 7"




