apiVersion: v1
kind: Service
metadata:
  name: flaskapp-service
  namespace: final 
spec:
  selector:
    app: flaskapp  
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 81  
  type: LoadBalancer
