apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 681863550751.dkr.ecr.us-east-1.amazonaws.com/mysql-image:latest  # ECR image URL
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret  # Secret name
              key: DBPWD  # Key for the password inside the secret
        - name: MYSQL_DATABASE
          value: employees  # Default database name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret  # Secret name
              key: DBUSER  # Key for the username inside the secret
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc