apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: final
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  # Ensure this matches the size of the PV
  storageClassName: gp2  # Ensure this matches the storage class of the PV


